### PR TITLE
Fix running from an installed version (Fix #618, Fix BlueBrain/Livre#379)

### LINKED ISSUE #618: NoThing working after make install (Ubuntu)
Hello;

Using Equalizer with Livre project

Built using Livre Cmake.

Building: OK
Running demo from build location: OK
Install in custom location, run the demo: KO 

9 Initializing compression DSO /data_local/j0334308/Livre_build/lib/libPression.so.2.0.0 failed, 0 compression engines reported
Erreur de segmentation (core dumped)

Demo KO when target thee INSTALL/lib location
Demo OK when target thee BUILD_LOCATION/lib location

My feeling is some environnement variable are recorded in the lib for plugin loading.

Any idea to help me?

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
Hold this horse - need to verify that plugins are loaded.

**Comment by eile** [comment]
Please shoot the horse now.

**Comment by ErwannH** [comment]
Great! It works... Thanks.

Just one detail. I need to integrate Livre in a QT app. I compiled  Equalizer with QT support. 

I'm using distributed QT 5 devel packages.

To make it compile I need to change a litlle bit QuickRenderer.cpp in Deflect

line 50:

#ifdef DEFLECT_USE_QT5GUI

#include <QOpenGLContext>
QT_BEGIN_NAMESPACE
	Q_GUI_EXPORT QOpenGLContext *qt_gl_global_share_context();
QT_END_NAMESPACE

#endif

and replace calls 

#if DEFLECT_USE_QT5GUI
        qt_gl_global_share_context( );
#else
        qWarning() << "DeflectQt was not compiled with WebEngineView support";
#endif
}

**Comment by eile** [comment]
Can you please submit a pull request in Deflect with this change?

**Comment by rdumusc** [comment]
Yes, I'm already looking into this. The compilation error must be because the private headers are not installed and CMake did not catch it for some reason, despite the check that sets DEFLECT_USE_QT5GUI. 

This suggestion to forward-declare the function instead of including the private header looks reasonable as I discovered that it is how it is done internally in QtWebengine:
https://git.merproject.org/mer-core/qtbase/commit/219c2eb4e28dd1c806cbc2115ff40454d6d3f9c5   
http://code.qt.io/cgit/qt/qtwebengine.git/commit/?id=f77967d96d161c791b0f49e73b243019b5ab484a

Note that the above code should use qt_gl_set_global_share_context(QOpenGLContext* context) (setter) and not QOpenGLContext *qt_gl_global_share_context() (getter).

I will submit a patch later today.

**Pull request merged**
