### PR TITLE
Add Client::addActiveLayout to tweak default autoconfigured layout

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by eile** [comment]
Should imo be done in Livre. Most other applications can handle Dynamic2D correctly.

Or do you have another reason to do this here?

**Comment by tribal-tec** [comment]
I'd vote the other way around. If your app can handle 2D easily, do it there. 'Simple' seems are more sensible default to me

**Comment by tribal-tec** [comment]
updated

**Comment by tribal-tec** [comment]
ping

**Pull request merged**
