### PR TITLE
EqGLLibraries: export correct GLEW_MX lib

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
+1

**Comment by eile** [comment]
Retest this please.

**Comment by eile** [comment]
Retest this please.

**Comment by eile** [comment]
Retest this please.

**Comment by tribal-tec** [comment]
Retest this please

**Comment by tribal-tec** [comment]
This time a real error

**Comment by eile** [comment]
Retest this please.

**Comment by tribal-tec** [comment]
No dot at the end, otherwise your command to trigger a build does not work!

**Comment by eile** [comment]
Retest this please

**Pull request merged**
