### PR TITLE
Use <> includes to avoid other config.h files in the search path (I'm looking at you, ITK!)

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Really? Why only in this file? These are local includes, so what the heck? Comment at least in the file to know why? Bug to reference in ITK?

**Comment by tribal-tec** [comment]
No +1, why merged?

**Comment by tribal-tec** [comment]
Where is the revert/proper fix for this?

**Comment by eile** [comment]
Error on my end. Comment addressed in 97ee34c

**Pull request merged**
